ALTER TABLE "Merchant" ADD COLUMN IF NOT EXISTS "kycNotes" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Merchant" ADD COLUMN IF NOT EXISTS "pixKey" TEXT;
ALTER TABLE "Merchant" ADD COLUMN IF NOT EXISTS "pixKeyType" TEXT;
ALTER TABLE "Merchant" ADD COLUMN IF NOT EXISTS "bankName" TEXT;
