ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastLoginAt"  TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastLoginIp"  TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastLoginUa"  TEXT;
