ALTER TABLE "Merchant" ADD COLUMN "reservedBalance" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Merchant" ADD COLUMN "blockedBalance" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Merchant" ADD COLUMN "futureBalance" DOUBLE PRECISION NOT NULL DEFAULT 0;
